### ISSUE TITLE
Some links in READMEs are rewritten incorrectly

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/hackage-server#823] opened 2019-04-10 19:19 UTC
Originally reported [here](https://github.com/haskell/cabal/issues/5980).

[In the readme for the `cabal-install` package on Hackage](http://hackage.haskell.org/package/cabal-install-2.4.1.0#readme) the `[bootstrap.sh]` link in the original markdown gets rewritten to point to http://hackage.haskell.org/package/cabal-install-2.4.1.0/cabal-install-2.4.1.0/srcbootstrap.sh. The correct destination should be http://hackage.haskell.org/package/cabal-install-2.4.1.0/src/bootstrap.sh.

**Comment by 23Skidoo** [comment] 2019-04-10 19:22
Also the `bootstrap.sh` file should probably be served as `text/plain` so that I could inspect it in the browser (currently I get a download prompt).

**Comment by 23Skidoo** [comment] 2019-04-10 19:24
Note that GitHub, for example, [renders this link correctly](https://github.com/haskell/cabal/tree/master/cabal-install#installing-the-cabal-command-line-tool).

**Comment by hvr** [comment] 2019-04-11 11:51
This looks like a one-liner fix... want to give it a stab? :-)

**Comment by 23Skidoo** [comment] 2019-04-11 11:55
Maybe...

**Comment by andreasabel** [comment] 2022-02-10 08:52
This issue needs a new reproducer or should be closed. (The evidence for the OP is no longer there.)

**Comment by gbaz** [comment] 2022-02-10 21:30
Optimistically closing.

**Closed by gbaz** 2022-02-10 21:30 UTC
Labels: bug
