### ISSUE TITLE
hackage-mirror error code 410

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#484] opened 2016-03-17 15:15 UTC
I got the following error while mirroring the public server:

hackage-mirror: Failed to download package hermes-1.3.4.3,
  HTTP error code 410, Gone 
  http://hackage.haskell.org/package/hermes-1.3.4.3/hermes-1.3.4.3.tar.gz

This seems to be a problem with this particular package, and I've not gotten the same error with any other packages. Unfortunately, the error kills hackage-mirror, and when I restart it, it immediately tries to grab hermes-1.3.4.3 again. Hackage-mirror should blacklist the package in this case so that it doesn't try to mirror it again.

**Comment by crockeea** [comment] 2016-03-19 03:14
tslib-0.1.4 seems similarly broken. It seems that upon failure, hackage-mirror is not adding hermes-1.3.4.3 or tslib-0.1.4 to "mirror-cache/unmirrorable-hackage-mirror"

**Comment by gbaz** [comment] 2016-04-28 12:59
Agreed this is a bug with hackage mirror. There are rare packages on hackage that don't exist by design, as they were in-house packages accidentally uploaded to the public hackage, and then behind-the-scenes removed/deleted once the error was realized. So hackage-mirror should be able to work around this sort of mess.

**Comment by dcoutts** [comment] 2016-05-15 13:08
This is fixed in the repo. The osuosl mirror has been using the fix and running fine for some time (though I recently stopped it for unrelated reasons).

**Closed by dcoutts** 2016-05-15 13:08 UTC
