### ISSUE TITLE
suggestion: list dependent packages?

### ISSUE THREAD

**Issue by tycho01** [haskell/hackage-server#767] opened 2018-07-01 12:16 UTC
One interesting feature on npmjs.com is that aside from package dependencies, it also lists [dependent packages](https://www.npmjs.com/package/ramda?activeTab=dependents).
Might it be an idea to try something similar on Hackage?

**Comment by phadej** [comment] 2018-07-01 12:42
duplicate of https://github.com/haskell/hackage-server/issues/40

But http://packdeps.haskellers.com/reverse/aeson is usable. I think we could add a link to `packdeps` site for time being, until #40 (#551 unstalled?) is done properly?

**Comment by phadej** [comment] 2018-07-01 12:45
Note: that `packdeps` lists reverse dependencies for the latest version of the package. I think that's not good enough for Hackage (it's good heurstic, but imprecise). Also it includes test-suites and benchmarks (and doesn't differentiate between them, i.e. doesn't list which component has the dependency - that's useful too)

**Comment by gbaz** [comment] 2019-01-19 04:49
closing as a dup

**Closed by gbaz** 2019-01-19 04:49 UTC
