### ISSUE TITLE
[Visual Bug] Floating footer bar

### ISSUE THREAD

**Issue by fosskers** [haskell/hackage-server#715] opened 2018-03-20 18:22 UTC
For packages with sufficiently short description / module sections, the gray footer seems to float (it's not sticky to the bottom of the page):

![2018-03-20-112022_1918x1078_scrot](https://user-images.githubusercontent.com/229679/37674827-f3a0071e-2c30-11e8-8573-e776e57e8d97.png)

**Comment by gbaz** [comment] 2018-03-20 19:31
cc @NunoAlexandre

**Comment by NunoAlexandre** [comment] 2018-03-21 08:03
You can assign it to me, @gbaz :+1:

**Comment by NunoAlexandre** [comment] 2018-03-23 21:35
@fosskers in which browser and device did you find this issue? I can't reproduce it using Chrome or Firefox.

**Comment by fosskers** [comment] 2018-03-23 22:43
I'm currently getting the visual bug in Firefox 59.0.1 on Arch Linux.

**Comment by gbaz** [comment] 2018-03-23 23:20
I see this issue in ffox and chrome both on my mac. I just need a package with a sufficiently small right-bar too. so, e.g. http://hackage.haskell.org/package/mbox-0.3

I can also get it with other packages that are a bit bigger by bumping down the size with cmd-minus.

**Comment by NunoAlexandre** [comment] 2018-03-24 08:34
Hm alright, thanks! I am refactoring and tuning some styling, I will take care of this in the same branch.

**Comment by NunoAlexandre** [comment] 2018-03-25 14:42
I was able to reproduce and to fix this issue. The fix is part of the #731 PR. Once that is merged this should be automatically closed. Thanks, @fosskers, for reporting it :+1:

**Closed** 2018-03-30 19:02 UTC
Labels: component: ux

**Comment by fosskers** [comment] 2018-03-30 20:03
What's the release schedule like for when fixes like this are implemented?
