### ISSUE TITLE
Right-hand block (properties table) can overlap readme.

### ISSUE THREAD

**Issue by vagarenko** [haskell/hackage-server#703] opened 2018-03-19 15:49 UTC
![simple vec3 three dimensional vectors of doubles with basic operations](https://user-images.githubusercontent.com/1395677/37606251-d7ec13a2-2bb6-11e8-919a-ed818355e4d9.png)

The right block overlaps readme section.

https://hackage.haskell.org/package/simple-vec3

**Comment by gbaz** [comment] 2018-03-19 16:05
This was by design, but I knew it might not be optimal. In particular, I didn't want to insert a `clear:both` above the readme, as it might cause an unexplainable/unfortunate gap of white-space. The alternative was to allow overlap. The remaining question is whether to have some sort of border or something, which I'm less keen on.

The alternative, which I've been thinking about, is in a future release just to drop the yellow background from the readme, which would make this sort of overlap much less intrusive.

Not sure of the best approach here...

**Comment by phadej** [comment] 2018-03-19 18:39
E.g. for `yaml` on resolution it's quite bad (on my resolution): (i.e. many versions, short `description`)

![screenshot from 2018-03-19 20-36-55](https://user-images.githubusercontent.com/51087/37615179-508222ea-2bb5-11e8-93e3-f6b952753f9c.png)

**Comment by gbaz** [comment] 2018-03-19 18:52
Good example! But the text rewraps -- so its essentially a visual artifact. The problem is what to do about it -- as I suggested, removing the yellow background (or turning it grey) could help. Not sure about other possibilities...

Another option could be to force two-col all the way down. But for many other packages that will lead to a lot of wasted space at the bottom...

There's also the question if we want some sort of auto-condensing of "versions" in general, which could declutter things. (I know some people always want them all by default, so we'd need a way to ensure that could be set, maybe with a cookie or something).

**Comment by gbaz** [comment] 2018-03-19 19:36
hmm... maybe some clever css could force the readme to narrow if _any part_ overlaps the floated properties table. If anyone halfway-competent at css wants to take a crack at this, please do!

**Comment by gbaz** [comment] 2018-03-20 05:49
here's what happens with a border, i think it's worse.

![image](https://user-images.githubusercontent.com/1125849/37636180-f14eaf56-2bd6-11e8-9a0a-c157216ccfba.png)

now here it is if we ditch the yellow background for embedded readme files for a more subtle effect (just the left hand border rule)

![image](https://user-images.githubusercontent.com/1125849/37636513-f91c8e86-2bd8-11e8-93e9-7685128edc5e.png)

I think that's a clean solution, in general, and ditching the yellow is more in keeping with the new theme. Thoughts?

**Comment by gwils** [comment] 2018-03-20 05:52
+1 from me, FWIW.
I didn't like the yellow with the old theme nor with this one.

**Comment by ShrykeWindgrace** [comment] 2018-03-20 15:11
@gbaz the "white-and-white" solution, imho, solves the awkward yellow shapes but kills the readability of the page all-together. The "yellow-and-border"  version is much better.

**Comment by gbaz** [comment] 2018-03-20 15:12
can you expand on why it kills the readability of the page? is the yellow background really necessary for README files?

**Comment by gbaz** [comment] 2018-03-21 03:20
Another approach is having it be a real two-col layout instead of a floating div. There is an implementation of this in https://github.com/haskell/hackage-server/pull/719 which results in

![hackage-after](https://user-images.githubusercontent.com/1002726/37689074-6fa0975a-2c79-11e8-8653-af848aa537e0.png)

**Comment by ShrykeWindgrace** [comment] 2018-03-21 14:45
@gbaz no, it is not the white or yellow, it is a lack of distinction between content areas and their respective placement. E.g., I start to read the second paragraph of the description ("This package includes the..."), then suddenly I see the "Uploaded" field in bold. The jigsaw puzzle of left-aligned text of the description and right-aligned text of technical info just seem awkward and misaligned, these lines should not be glued together.

On top of that, wide codeblocks without wraps in package description now have horizontal scrollbars, yet these examples are one of the main reasons to visit the package description page.

The real two column layout seems to be less awkward.

**Comment by gbaz** [comment] 2018-03-21 15:27
There is another ticket for left-aligned descriptions at https://github.com/haskell/hackage-server/issues/716, and you get something like this:  

![image](https://user-images.githubusercontent.com/1125849/37693150-28539bb6-2c94-11e8-9fed-03b1cff6d02a.png)

so that might fix up the readability as well?

**Comment by lspitzner** [comment] 2018-03-21 23:03
A random, stupid idea: Make both columns separately scrollable.

A not so random thought: It is stupid to fight against too high elements when there still are margins on the sides. After all the purpose of such margins is to keep the central text from becoming too broad, but that does not really apply to the "properties", does it? So: give all remaining space to the properties, remove any generous margins on the sides.

**Comment by gbaz** [comment] 2018-03-27 03:12
I think the combination of the vertical table layout as suggested in #731 

<img src="https://user-images.githubusercontent.com/1125849/37944527-f039526a-3149-11e8-88e2-28013dd1da11.png" width="300">

along with swapping the yellow for a border-rule

should resolve this?

**Comment by gbaz** [comment] 2018-03-30 22:48
closing this as resolved on the basis of those two changes.

**Closed by gbaz** 2018-03-30 22:48 UTC
Labels: component: ux, discussion
