### ISSUE TITLE
Documentation rebuilds don't seem to work

### ISSUE THREAD

**Issue by revnull** [haskell/hackage-server#542] opened 2016-09-14 12:15 UTC
A package of mine failed the documentation build (which itself may be an issue worth raising), but I clicked the "delete documentation and trigger rebuild" button (after setting more lenient dependencies), which did not actually trigger another rebuild.

The package is at https://hackage.haskell.org/package/implicit-logging

**Comment by bgamari** [comment] 2016-09-15 15:15
Thanks for this report! It looks like the issue is that the package excludes the `base` version provided by the GHC release run on the doc builder (evidently GHC 8.0.1 now),
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: implicit-logging-0.2.0.0 (user goal)
next goal: base (dependency of implicit-logging-0.2.0.0)
rejecting: base-4.9.0.0/installed-4.9... (conflict: implicit-logging =>
base>=4.8 && <4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Dependency tree exhaustively searched.
```

Really this should fail with a better error message. As for the bounds issue, I'm not sure how the doc builder should deal with this situation.

**Comment by bgamari** [comment] 2016-09-15 15:19
Oh, perhaps I mis-read your report: you said you set more lenient dependencies; how exactly did you go about doing this?

**Comment by gbaz** [comment] 2016-09-19 20:31
@bgamari I think the main issue here is that we have this button that says it triggers a rebuild, but by our current docbuilder setup apparently does nothing :-)

**Comment by gbaz** [comment] 2016-10-25 16:48
Closing this in favor of https://github.com/haskell/hackage-server/issues/515 which I think is the same issue? correct me if wrong.

**Closed by gbaz** 2016-10-25 16:48 UTC
Labels: component: doc builder
