### ISSUE TITLE
default package list should not contain duplicates

### ISSUE THREAD

**Issue by lspitzner** [haskell/hackage-server#326] opened 2015-02-24 22:00 UTC
could we make the default package list (https://hackage.haskell.org/packages/) not contain duplicates? i.e. not be sorted by category? categories are worthless anyway..

reason: i searched the package list by looking at the full list and searching for a specific phrase. duplicates are annoying, as i find the same package multiple times in such a case (and it certainly was not the first time this happens; but i do not think of using /names every time. the default simply should be better.)

**Comment by alpmestan** [comment] 2015-02-24 23:06
Wouldn't the searchbox do a better job in your case? It doesn't display duplicates.

**Comment by lspitzner** [comment] 2015-02-24 23:26
it does not do the same. seach for "cabal". you get results that do not contain the phrase "cabal", regardless of whether you look at result list or in the complete package list. same for the phrase "ghc". maybe because they are widely used package names, but regardless of the exact reason it does not help my trust in what the searchbox exactly does. directly searching the full site is more transparent, and should work just as fine.

**Comment by dcoutts** [comment] 2015-03-03 20:41
@lspitzner that's because it searches more than just the package name. This is a feature not a bug :-)
It also searches the package description (but scores it lower than the name or synopsis)

**Comment by lspitzner** [comment] 2015-03-03 21:25
as it is, it is an undocumented, intransparent feature that does not work too well in my experience. this probably is not the tools fault; we would need some proper keywords in the packages or something of the sort to get better results.

and this is all slightly off the mark - i should ask back: what is the advantage in having a default list be sorted by categories? when i come to the website, click browse, and get something that looks like a long list of stuff, i would expect this to be a full, duplicate-free listing. yes, there is a headline mentioning categories at the top - which easily is either overlooked or mistaken as some form of navigation thingy.

i do not want to remove the list-by-category nor the search box. i simply vote for a different default.

**Comment by dcoutts** [comment] 2015-03-04 22:16
I think we should completely rethink the approach to browsing. If one is not going by search/keyword then what browse interface is sensible?  One big list is really just search with a bad interface.

**Comment by dcoutts** [comment] 2015-03-04 22:17
And yes, I do want to have extra keywords (categories, extra keywords, aliases) and use those in the search too.

**Comment by gbaz** [comment] 2017-09-22 14:28
https://github.com/haskell/hackage-server/pull/552 will switch to a default package list (browsable) that doesn't have duplicates.

**Comment by gbaz** [comment] 2018-01-28 02:52
fixed with above merge

**Closed by gbaz** 2018-01-28 02:52 UTC
