### ISSUE TITLE
Missing package.json files in 01-index.tar

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#623] opened 2017-09-22 13:10 UTC
The 01-index.tar archive contains a file `package.json` for most packages, but not for all. For `hzaif-0.1.0.0`, for example, has a Cabal file  but no meta information. Is that intentional?

**Comment by hvr** [comment] 2017-09-22 15:49
No, it is not intentional; and it's a hard to reproduce bug that resulted in those missing entries

as this is basically a duplicate of #488 I'm closing this

**Closed by hvr** 2017-09-22 15:49 UTC
Labels: duplicate
