### ISSUE TITLE
Tables in readme markdown

### ISSUE THREAD

**Issue by expipiplus1** [haskell/hackage-server#877] opened 2020-05-29 14:40 UTC
Is it possible to render tables in the markdown readmes of packages. At the moment they don't render at all well

An example: https://hackage.haskell.org/package/orbits-0.3 (from https://github.com/expipiplus1/orbits#nomenclature)

**Comment by Bodigrim** [comment] 2020-06-24 20:28
More examples:
https://hackage.haskell.org/package/random-1.2.0#readme
https://hackage.haskell.org/package/mod-0.1.1.0#readme
https://hackage.haskell.org/package/poly-0.4.0.0#readme

**Comment by lehins** [comment] 2020-06-24 20:46
I think it might be a duplicate of #565 

Markdown files, such as changelog.md and readme.md are viewed on both Github and Hackage. It would be nice to have a consistent looking pages between the two. 

With more and more packages relying on tables, I think this issue does deserve some attention.

**Comment by phadej** [comment] 2020-06-24 22:41
There is a plan in #565, either vendor in `commonmark-...` packages, or we can depend on `pandoc`.

Closing this as duplicate.

**Closed by phadej** 2020-06-24 22:41 UTC

**Comment by expipiplus1** [comment] 2020-06-26 04:49
Cool, thanks @phadej

**Comment by andreasabel** [comment] 2020-12-28 15:12
There is PR #904.  Hope this will go live soon and fix the problem.

**Comment by expipiplus1** [comment] 2020-12-28 17:14
thanks！
