### ISSUE TITLE
Cabal Revision files change line encoding. Breaking subsequent patches.

### ISSUE THREAD

**Issue by angerman** [haskell/hackage-server#712] opened 2018-03-20 06:03 UTC
```
$ cabal unpack --pristine free
$ file free-5.0.1/free.cabal
free-5.0.1/free.cabal: ASCII text
```
however
```
$ cabal unpack free
$ file free-5.0.1/free.cabal       
free-5.0.1/free.cabal: ASCII text, with CRLF line terminators
```

Similarly downloading a revision from `http://hackage.haskell.org/package/<package>/revision/<n>.cabal`; yields `CRLF` line terminators.

This is terrible. The revision should not alter there the line terminators.

As such any patch atop a hackage package will break after a revision if the package didn't
have `CRLF` line terminators before the revision.

Why does hackage change the line terminators on revisions?

**Comment by gbaz** [comment] 2018-03-20 19:35
Duplicate of #316

**Comment by gbaz** [comment] 2018-03-20 19:37
closing in favor that bug.

**Closed by gbaz** 2018-03-20 19:37 UTC
