### ISSUE TITLE
Two-column layout overlaps metadata over README

### ISSUE THREAD

**Issue by lambdageek** [haskell/hackage-server#718] opened 2018-03-20 22:06 UTC
See attached screenshot - when the package description is short and there are not a lot of modules, the metadata column will overlap the README.  It looks like the README content wraps properly, so nothing is missing - it's just a little visual quirk.

![hackage-2col-clash](https://user-images.githubusercontent.com/480437/37685320-6d4538c2-2c69-11e8-8665-72b749b831f3.png)

**Comment by gbaz** [comment] 2018-03-20 22:11
Duplicate of #703

**Closed by gbaz** 2018-03-20 22:11 UTC
