### ISSUE TITLE
Hackage's rendering of Licenses, or how to get `GPL-3.0-or-later`?

### ISSUE THREAD

**Issue by juhp** [haskell/hackage-server#782] opened 2018-07-30 03:47 UTC
I think the rendering of package License fields on Hackage has changed?

For example GPL-3 is rendered as `GPL-3.0-only` on Hackage,
but the `GPL-3` field in .cabal files also covers `GPL-3-or-later` for example.
Or maybe there is already a way to do it correctly?

**Comment by juhp** [comment] 2018-07-30 03:54
Ah, I guess this is haskell/cabal#2547 and #385, so it requires Cabal 2.2.
Then presumably it only works with Cabal >= 2.2.

**Comment by gbaz** [comment] 2018-07-30 03:56
old style licenses are i think converted to spdx ones when we render them. But the conversion function indeed converts gpl-3 to gpl only: http://hackage.haskell.org/package/Cabal-2.2.0.1/docs/src/Distribution-License.html#licenseToSPDX

**Comment by gbaz** [comment] 2018-07-30 03:57
(i.e. it does not cover 3-or-later)

**Comment by gbaz** [comment] 2018-07-30 14:11
On second thought, maybe it isn't correct to render gpl3 to gpl-3-only. Rather, for the "only" conversion cases (where we err on the side of conservative in the conversion) we perhaps should be rendering the _unconverted_ thing rather than introducing spurious choices.

**Comment by phadej** [comment] 2018-07-30 14:36
Note that GPL-3.0 are registered into ghc-pkg (8.4+) database as `GPL-3.0-only`, so if authors really care, they should bump to `cabal-version: 2.2` and use proper expression.

The SPDX team introduced `GPL-3.0-only` and `GPL-3.0-or-later` identifiers specifically to avoid confusion of what's meant by `GPL-3.0` (and too subtle difference with `GPL-3.0+`, which we don't even accept to Hackage. One can write `GPL-3.0-only+` though; which we can forbid to enter Hackage though - not sure if we actually do).

**Comment by gbaz** [comment] 2018-07-30 16:02
Right, but the problem is we have a ton of packages which _do_ have that confusion already. So my idea here is to not "force" a choice on the author, retroactively, but just allow that confusion to persist in older-style cabal files.

**Comment by gbaz** [comment] 2018-07-30 16:47
Actually, starting to change my mind again. After reading through the gpl faq, it seems to me like the "ambiguity" in not specifying only or or-newer really isn't that ambiguous. Without an explicit "or newer" designation the only _possible_ reading is "only". So I'm starting to think that until cabal 2.2 there really just _was_ no way to say "or newer" and the status quo now just recognizes that fact...

**Comment by gbaz** [comment] 2021-06-07 01:29
based on my last thinking in this thread and no further discussion, optimistically closing.

**Closed by gbaz** 2021-06-07 01:29 UTC
